#!/usr/bin/env python3
# Copyright 2026 JB
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
import sys

from graph_dashboard.server import main

if __name__ == "__main__":
    sys.exit(main())
